require "./lib/rng.rb"

class CatFacts
  def random_fact
    facts.shuffle(random: SecureRandom::RNG).first
  end

  private
  def facts
    [   
        "A cat has more bones than a human; humans have 206, but the cat has 230 (some cites list 245 bones, and state that bones may fuse together as the cat ages).",
        "Cats respond better to women than to men, probably due to the fact that women's voices have a higher pitch.",
        "A steady diet of dog food may cause blindness in your cat - it lacks taurine. ",
        "The cat does not exist in the Chinese Zodiac, but it does in the Vietnamese version, instead of rabbit.",
        "The Maine Coon cat is America's only natural breed of domestic feline. It is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
        "Female cats are \"polyestrous,\" which means they may have many heat periods over the course of a year. A heat period lasts about 4 to 7 days if the female is bred; if she is not, the heat period lasts longer and recurs at regular intervals.",
        "Cats have 30 vertebrae--5 more than humans have.",
        "Ancient Egyptian family members shaved their eyebrows in mourning when the family cat died.",
        "When your cats rubs up against you, she is actually marking you as \"hers\" with her scent. If your cat pushes his face against your head, it is a sign of acceptance and affection.",
        "Almost 10% of a cat's bones are in its tail, and the tail isused to maintain balance.",
        "Cats have 32 muscles that control the outer ear (compared to human's 6 muscles each). A cat can rotate its ears independently 180 degrees, and can turn in the direction of sound 10 times faster than those of the best watchdog.",
        "Cats take between 20-40 breaths per minute.",
        "In ancient Egypt, when a family cat died, all family members would shave their eyebrows as a sign of mourning.",
        "Neutering a cat extends its life span by two or three years.",
        "Retractable claws are a physical phenomenon that sets cats apart from the rest of the animal kingdom.",
        "Of all the species of cats, the domestic cat is the only species able to hold itstail vertically while walking. All species of wild cats hold their talk horizontally or tucked between their legs while walking.",
        "A cat has a total of 24 whiskers, 4 rows of whiskers on each side. The upper two rows can move independently of the bottom two rows. ",
        "Cats can be taught to walk on a leash, but a lot of time and patienceis required to teach them. The younger the cat is, the easier it will be for them to learn.",
        "Besides smelling with their nose, cats can smell with an additional organ called the Jacobson's organ, located in the upper surface of the mouth.",
        "Cats must have fat in their diet because they can't produce it on their own.",
        "Cats have a special scent organ located in the roof of their mouth, called the Jacobson's organ. It analyzes smells - and is the reason why you will sometimes see your cat \"sneer\" (called the flehmen response or flehming) when they encounter a strong odor.",
        "Cats can judge within 3 inches the precise location of a sound being made 1 yard away.",
        "Almost 10% of a cat's bones are in its tail, and the tail is used to maintain balance.",
        "The cat's clavicle, or collarbone, does not connect with other bones but is buried in the muscles of the shoulder region. This lack of a functioning collarbone allows them to fit through any opening the size of their head.",
        "Abraham Lincoln loved cats. He had four of them while he lived in the White House.",
        "Cats have been domesticatedfor half as long as dogs have been.",
        "Cat litter was \"invented\" in 1947 when Edward Lowe asked his neighbor to try a dried, granulated clay used to sop up grease spills in factories. (In 1990, Mr. Lowe sold his business for $200 million.)",
        "In the Middle Ages, during the Festival of Saint John, cats were burned alive in town squares.",
        "Normal body temperature for a cat is 102 degrees F.",
        "Today there are about 100 distinct breeds of the domestic cat.",
        "A form of AIDS exists in cats.",
        "The Maine Coon is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
        "Contrary to popular belief, people are not allergic to cat fur, dander, saliva, or urine - they are allergic to \"sebum,\" a fatty substance secreted by the cat's sebaceous glands. More interesting, someone who is allergic to one cat may not be allergic to another cat. Though there isn't (yet) a way of predicting which cat is more likely to cause allergic reactions, it has been proven that male cats shed much greater amounts of allergen than females. A neutered male, however, sheds much less than a non-neutered male.",
        "Tylenol and chocolate are both poisionous to cats.",
        "A cat will tremble or shiver when it is in extreme pain.",
        "A cat uses its whiskers for measuring distances.  The whiskers of a cat are capable of registering very small changes in air pressure.",
        "Cat's urine glows under a black light.",
        "In 1987, cats overtook dogs as the number one pet in America (about 50 million cats resided in 24 million homes in 1986). About 37% of American homes today have at least one cat.",
        "Cats have 30 teeth (12 incisors, 10 premolars, 4 canines, and 4 molars), while dogs have 42. Kittens have baby teeth, which are replaced by permanent teeth around the age of 7 months.",
        "If your cat snores or rolls over on his back to expose his belly, it means he trusts you.",
        "In Siam, the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.",
        "Cats are subject to gum disease andto dental caries. They should have their teeth cleaned by the vet or the cat dentist once a year.",
        "The chlorine in fresh tap water irritates sensitive parts of the cat's nose. Lettap water sit for 24 hours before giving it to a cat.",
        "If a cat is frightened, put your hand over its eyes and forehead, or let him bury his head in your armpit to help calm him.",
        "Cats can't taste sweets.",
        "A happy cat holds her tail high and steady.",
        "Purring not always means happiness. Purring could mean a cat is in terrible pain such as during childbirth. Kitten will purr to their mother to let her know they are getting enough milk while nursing. Purring is a process ofinhaling and exhaling, usually performed while the mouth is closed. But don't worry, if your cat is purring while your gently petting her and holding her closeto you - that is a happy cat!",
        "The ancestor of all domestic cats is the African Wild Cat which still exists today.",
        "A cat's brain is more similar to a man's brain than that of a dog.",
        "The first true cats came into existence about 12 million years ago and were the Proailurus.",
        "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
        "The first cat show was in 1871 at the Crystal Palace in London.",
        "Phoenician cargo ships are thought to have brought the first domesticated cats to Europe in about 900 BC.",
        "Many cats cannot properly digest cow's milk. Milk and milk products give them diarrhea.",
        "Tabby cats are thought to get their name from Attab,a district in Baghdad, now the capital of Iraq.",
        "In an average year, cat owners in the United States spend over $2 billion on cat food.",
        "Cats' hearing is much more sensitive than humans and dogs.",
        "According to a Gallup poll, most American pet owners obtain their cats by adopting strays.",
        "The average cat food meal is the equivalent to about five mice.",
        "A female cat will be pregnant for approximately 9 weeks - between 62 and 65 days from conception to delivery.",
        "Not every cat gets \"high\" from catnip. If the cat doesn't have a specific gene, it won't react (about 20% do not have the gene). Catnip is non-addictive.",
        "ix-toed kittens are so common in Boston and surrounding areas of Massachusetts that experts consider it an established mutation.",
        "The silks created by weavers in Baghdad were inspired by the beautiful and varied colors and markings of cat coats. These fabrics were called \"tabby\" by European traders.",
        "Neutering a male cat will, in almost all cases, stop him from spraying (territorial marking), fighting with other males (at least over females), as well as lengthen his life and improve its quality.",
        "A cat's field of vision is about 200 degrees.",
        "The cat's front paw has 5 toes, but the back paws have 4. Some cats are born with as many as 7 front toes and extra back toes (polydactl).",
        "Miacis, the primitive ancestor of cats, was a small, tree-living creature of the late Eocene period, some 45 to 50 million years ago.",
        "Cats purr at the same frequency as an idling diesel engine, about 26 cycles per second.",
        "Cats have 30 vertebrae (humans have 33 vertebrae during early development; 26 after the sacral and coccygeal regions fuse)",
        "Both humans and cats have identical regions in the brain responsible for emotion.",
        "A cat's normal pulse is 140-240 beats per minute, with an average of 195.",
        "Never give your cat aspirin unless specifically prescribed by your veterinarian; it can be fatal. Never ever give Tylenol to a cat.  And be sure to keep anti-freeze away from all animals - it's sweet and enticing, but deadly poison.  ",
        "Cats do not think that they are little people. They think that we are big cats. This influences their behavior in many ways.",
        "Cats can be right-pawed or left-pawed.",
        "The cat appears to be the only domestic companion animal not mentioned in the Bible. *",
        "A male cat is called a \"tom\" (or a \"gib,\" if neutered), and a female is called a \"molly\" or \"queen.\" The father of a cat is its \"sire,\" and mother is its \"dam.\" An immature cat of either sex is called a \"kitten.\" A group of cats is a \"clowder.\"",
        "The color of the points in Siamese cats is heat related. Cool areas are darker.",
        "The first breeding pair of Siamese cats arrived in England in 1884.",
        "Cats dislike citrus scent.",
        "Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.",
        "The Maine Coone is the only native American long haired breed.",
        "A cat will spend nearly 30% of her life grooming herself.",
        "The wayyou treat kittens in the early stages of it's life will render it's personalitytraits later in life.",
        "When a domestic cat goes after mice, about 1 pounce in 3 results in a catch.",
        "Declawing a cat is the same as cutting a human's fingers off at the knuckle. There are several alternatives to a complete declawing, including trimming or a less radical (though more involved) surgery to remove the claws. Instead, train your cat to use a scratching post.",
        "The first formal cat show was held in England in 1871; in America, in 1895.",
        "The Pilgrims were the first to introduce cats to North America.",
        "Contrary to popular belief, the cat is a social animal. A pet cat will respond and answer to speech , and seems to enjoy human companionship.",
        "A cat has approximately 60 to 80 million olfactory cells (a human has between 5 and 20 million).",
        "Purring does not always indicate that a cat is happy and healthy - some cats will purr loudly when they are terrified or in pain.",
        "Cats have an average of 24 whiskers, arranged in four horizontal rows on each side.",
        "Many cats love having their forehead gently stroked.",
        "All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.",
        "A cat can jump 5 times as high as it is tall.",
        "Cat bites are more likely to become infected than dog bites.",
        "If a cat is frightened, the hair stands up fairly evenly all over the body; when the cat is threatened or is ready to attack, the hair stands up only in a narrow band along the spine and tail.",
        "Both humans and cats have identical regions in the brain responsible for emotion.",
        "When well treated, a cat can live twenty or more years but the average life span of a domestic cat is 14 years.",
        "A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds, slightly less for female housecats.",
        "In 1987 cats overtook dogs as the number one pet in America.",
        "Spaying a female before her first or second heat will greatly reduce the threat of mammary cancer and uterine disease. A cat does not need to have at least 1 litter to be healthy, nor will they \"miss\" motherhood. A tabby named \"Dusty\" gave birth to 420 documented kittens in her lifetime, while \"Kitty\" gave birth to 2 kittens at the age of 30, having given birth to a documented 218 kittens in her lifetime.",
        "Cats sleep 16 to 18 hours per day. When cats are asleep, they are still alert toincoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.",
        "A cat cannot see directly under its nose.",
        "Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.",
        "Cats walk on their toes.",
        "Cat families usually play best in even numbers. Cats and kittens should be aquired in pairs whenever possible.",
        "The catnip plant contains an oil called hepetalactone which does for cats what marijuana does to some people. Not all cats react to it those that do appear to enter a trancelike state. A positive reaction takes the form of the cat sniffing the catnip, then licking, biting, chewing it, rub & rolling on it repeatedly, purring, meowing & even leaping in the air.",
        "An estimated 50% of today's cat owners never take their cats to a veterinarian for health care. Too, because cats tend to keep their problems to themselves, many owners think their cat is perfectly healthy when actually they may be suffering from a life-threatening disease. Therefore, cats, on an average, are much sicker than dogs by the time they are brought to your veterinarian for treatment.  ",
        "A cat's brain is more similar to a man's brain than that of a dog.",
        "In ancient Egypt, killing a cat was a crime punishable by death.",
        "The domestic cat is the only species able to hold its tail vertically while walking. You can also learn about your cat's present state of mind by observing the posture of his tail.",
        "A cat has more bones than a human; humans have 206, and the cat - 230.",
        "While many cats enjoy milk, it will give some cats diarrhea.",
        "In ancient Egypt, mummies were made of cats, and embalmed mice were placed with them in their tombs. In one ancient city, over 300,000 cat mummies were found.",
        "Female felines are \"superfecund,\" which means that each of the kittens in her litter can have a different father.",
        "A cat sees about 6 times better than a human at night, and needs 1/6 the amount of of light that a human does - it has a layer of extra reflecting cells which absorb light.",
        "Julius Ceasar, Henri II, Charles XI, and Napoleon were all afraid of cats.",
        "A domestic cat can sprint at about 31 miles per hour.",
        "You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.",
        "The female cat reaches sexual maturity within 6 to 10 months; most veterinarians suggest spaying the female at 5 months, before her first heat period. The male cat usually reaches sexual maturity between 9 and 12 months.",
        "Experts traditionally thought that the Egyptians were the first to domesticate the cat, some 3,600 years ago.  But recent genetic and archaeological discoveries indicate that cat domestication began in the Fertile Crescent, perhaps around 10,000 years ago, when agriculture was getting under way. (per Scientific American, 6/10/2009)",
        "It may take as long as 2 weeks for a kitten to be able to hear well.  Their eyes usually open between 7 and 10 days, but sometimes it happens in as little as 2 days.",
        "Recent studies have shown that cats can see blue and green. There is disagreement as to whether they can see red.",
        "There are approximately 100 breeds of cat.",
        "Statistics indicate that animal lovers in recent years have shown a preference for cats over dogs!",
        "Cats come back to full alertness from the sleep state faster than any other creature.",
        "A cat's jaw has only up and down motion; it does not have any lateral, side to side motion, like dogs and humans.  ",
        "Baking chocolateis the most dangerous chocolate to your cat.",
        "Domestic cats purr both when inhaling and when exhaling.",
        "Cats bury their feces to cover their trails from predators.",
        "In just 7 years, one un-spayed female cat and one un-neutered male cat and their offspring can result in 420,000 kittens.",
        "Cats lap liquid from the underside of their tongue, not from the top.",
        "Mature cats with no health problems are in deep sleep 15 percent of their lives. They are in light sleep 50 percent of the time. That leaves just 35 percent awake time, or roughly 6-8 hours a day. ",
        "Blue-eyed, pure white cats are frequently deaf.",
        "A cat can sprint at about thirty-one miles per hour.",
        "Cats can jump up to 7 times their tail length.",
        "Notevery cat gets \"high\" from catnip. Whether or not a cat responds to it depends upon a recessive gene: no gene, no joy.",
        "Cats, especially older cats, do get cancer. Many times this disease can be treated successfully.",
        "A cat has two vocal chords, and can make over 100 sounds.",
        "The cat has 500 skeletal muscles (humans have 650).",
        "People who are allergic to cats are actually allergic to cat saliva or to cat dander. If theresident cat is bathed regularly the allergic people tolerate it better.",
        "Some notable people who disliked cats:  Napoleon Bonaparte, Dwight D. Eisenhower, Hitler.",
        "Cat families usually play best in even numbers. Cats and kittens should be acquired in pairs whenever possible.",
        "Cats have been domesticated for half as long as dogs have been.",
        "Unlike humans, cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.",
        "Cats that live together sometimes rub each others heads to show that they have no intention of fighting.",
        "Cats must have fat in their diet because they can't produce it on their own.",
        "Mother cats teach their kittens to use the litter box.",
        "Cats can get tapeworms from eating mice. If your cat catches a mouse it is best to take the prize away from it.",
        "Cats respond most readily to names that end in an \"ee\" sound.",
        "Cats should not be fed tuna exclusively, as it lacks taurine, an essential nutrient required for good feline health.  Make sure you have the proper Pet supplies to keep your cat happy and healthy.",
        "Like birds, cats have a homing ability that uses its biological clock,the angle of the sun, and the Earth's magnetic field. A cat taken far from its home can return to it. But if a cat's owners move far from its home, the cat can't find them.",
        "It has been scientifically proven that stroking a cat can lower one's blood pressure.",
        "The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer. Some cats have been documented to have a longevity of 34 years.",
        "A cat's tongue has tiny barbs on it.",
        "Cats' hearing stops at 65 khz (kilohertz); humans' hearing stops at 20 khz.",
        "A cats field of vision is about 185 degrees.",
        "The life expectancy of cats has nearly doubled since 1930 - from 8 to 16 years.",
        "Most cats adore sardines.",
        "Cats lived with soldiers in trenches, where they killed mice during World War I.",
        "A cat's whiskers are thought to be a kind of radar, which helps a cat gauge the space it intends to walk through.",
        "Some common houseplants poisonous to cats include: English Ivy, iris, mistletoe, philodendron, and yew.",
        "A cat can spend five or more hours a day grooming himself.",
        "Siamese kittens are born white because of the heat inside the mother's uterus before birth.This heat keeps the kittens' hair from darkening on the points.",
        "Jaguars are the only big cats that don't roar."
    ]
    end
  end