services:
  # A Ruby web service
  - type: web
    name: sinatra
    env: ruby
    repo: https://github.com/jeremy04/horse_time.git
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec puma

    autoDeploy: false # optional
  # A Redis instance
  - type: redis
    name: hammer
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
