services:
  # A Ruby web service
  - type: web
    name: horsetime
    env: ruby
    repo: https://github.com/jeremy04/horse_time.git
    plan: free
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec puma
    envVars:
      - key: REDISTOGO_URL
        fromService:
          type: redis
          name: hammer
          property: connectionString
    autoDeploy: false # optional

  # A Redis instance
  - type: redis
    name: hammer
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter)
    region: ohio
